### ISSUE TITLE
animation issue with different mocap data

### ISSUE THREAD

**Issue by rainstophan** [JLPM22/MotionMatching#3]
Hi, I kept the same setting and test it with different mocap data. It ended up look like this. Do you know the possible reason?😅
<img width="788" alt="Screenshot 2023-12-11 at 13 56 25" src="https://github.com/JLPM22/MotionMatching/assets/49219934/24dc58bf-868e-4f75-a5c2-646d35f2a754">
<img width="788" alt="Screenshot 2023-12-11 at 13 57 08" src="https://github.com/JLPM22/MotionMatching/assets/49219934/bc6056c9-6fe5-49d3-8461-3c4f08cc9b20">

**Comment by JLPM22** [comment]
Hi!

When changing the mocap there are some settings in the MMData that should be changed. That is, the animation with tpose,  the SkeletonToMecanim mapping, and from the images it looks like the Hips forward and up vectors should be updated as well. These vectors should be from the .bvh skeleton.

More information: https://jlpm22.github.io/motionmatching-docs/basics/animation_database/

Feel free to send me the .bvh file if you want me to take a look :)

**Comment by rainstophan** [comment]
Thanks for your kind response.😊 Below are the files I tested.
[subject1_tpose.bvh.txt](https://github.com/JLPM22/MotionMatching/files/13660595/subject1_tpose.bvh.txt)
[walk1_subject1.bvh.txt](https://github.com/JLPM22/MotionMatching/files/13660596/walk1_subject1.bvh.txt)


> Hi!
> 
> When changing the mocap there are some settings in the MMData that should be changed. That is, the animation with tpose, the SkeletonToMecanim mapping, and from the images it looks like the Hips forward and up vectors should be updated as well. These vectors should be from the .bvh skeleton.
> 
> More information: https://jlpm22.github.io/motionmatching-docs/basics/animation_database/
> 
> Feel free to send me the .bvh file if you want me to take a look :)

**Comment by JLPM22** [comment]
Hi!

I think with this configuration, it should work! I just tried it:
![image](https://github.com/JLPM22/MotionMatching/assets/45894435/041efe6a-9b47-4cc2-b85f-da8483b32899)

Remember to click Generate Databases again!

I guess the problem was the definition of the local hips vectors. For the next version of the package, I'll try to make a process to automatically compute these vectors to facilitate the incorporation of new motion capture data :)

Let me know if it works or there are any further problems!

**Comment by rainstophan** [comment]
Thx It works! Wait for your wonderful work~
